input_max_length: 16384,16384,16384
datasets: infbench_sum_eng_14984,infbench_qa_eng_16174,infbench_choice_eng_16174
generation_max_length: 1200,10,10
test_files: ',,'
demo_files: ',,'
use_chat_template: true
max_test_samples: 20
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
