input_max_length: 65536,65536,65536
datasets: narrativeqa_65236,infbench_qa_eng_65326,infbench_choice_eng_65326
generation_max_length: 100,10,10
test_files: ',,'
demo_files: ',,'
use_chat_template: true
max_test_samples: 20
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
