input_max_length: 32768,32768
datasets: infbench_sum_eng_31368,multi_lexsum_32068
generation_max_length: 1200,400
test_files: ','
demo_files: ','
use_chat_template: true
max_test_samples: 20
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
